### PR TITLE
Move UI Filters conversion to backend

### PR DESCRIPTION
**Pull request by sqren**
UI filters need to be converted from a simple object to and elasticsearch bool query. This PR moves that conversion from the client to the server.

### CODE REVIEW

**Comment by dgieselaar** [comment]
LGTM, one question: maybe we can handle stringifying plain objects inside of callApi?

**Comment by sqren** [comment]
> maybe we can handle stringifying plain objects inside of callApi?

I'm always hesitant of moving custom logic like this to generic components like `callApi`. It oftens ends up like:

```js
if (query.uiFilters) {
  // ...
} 

if (query.otherParam) {
  // ...
} else if (query.thirdParam) {
  // ..
}

// ad infinitum
```

And half of those conditions end up being dead code because the functions that call them have since been removed. 

Okay, I went a bit hyperbole but you get my drift 😅

**Comment by dgieselaar** [comment]
I don't know if it needs to be specific:
```javascript
if (typeof value === 'object') {
	value = JSON.stringify(value);
}
```

and optionally we could use `_.isPlainObject()` to be a little more specific.

**Comment by sqren** [comment]
@dgieselaar I tried to make the change but I'm having a hard time finding an elegant solution for typing this.

`KFetchOptions` doesn't support objects in `query` so I'll have to extend that. But even if I do I run into issues because `UIFilters` doesn't have an index signature. How would you type this without changing `UIFilters`?

**Comment by dgieselaar** [comment]
@sqren 	try:
```typescript
type KFetchQueryValues = KFetchQuery[''];
type Query = Record<
  string,
  KFetchQueryValues | Record<string, KFetchQueryValues>
>;

export async function callApi<T = void>(
  fetchOptions: Omit<KFetchOptions, 'query'> & {
    query?: Query;
  },
  options?: KFetchKibanaOptions
): Promise<T> {
```

**Comment by dgieselaar** [comment]
@sqren looks like the trick is changing UIFilters from an interface to a type 🤷‍♂

**Comment by sqren** [comment]
@dgieselaar Wow, that's bizarre! Good find, I'll change 👍

**Comment by sqren** [comment]
@dgieselaar I'm still having some issues getting it to work in an elegant way. I'll merge this for now so it's easier for you to base your changes on the other PR and then we can add the changes.

**Pull request merged**
